jwt:
  duration: 86_400_000 # 1 Day in miliseconds
  rsa:
    public: "/run/secrets/jwt-public-key"
    private: "/run/secrets/jwt-private-key"

eureka:
  client:
    service-url:
      defaultZone : http://service-registry:8761/eureka/