server:
  port: 8081
spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: ${MONGO_AUTH_DB}
      database: ${MONGO_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

jwt:
  duration: 86_400_000 # 1 Day in miliseconds
  rsa:
    public: "dev_public.der"
    private: "dev_private.der"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/