spring:
  application:
    name: authentication-service
  profiles:
    active: prod
  config:
    import:
      - optional:file:/run/secrets/database_config.yml

  datasource:
    hikari:
      maximum-pool-size: 5