spring:
  application:
    name: authentication-service
  profiles:
    active: prod
  config:
    import:
      - optional:file:/run/secrets/database_config.yml
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/