server:
  port: 8081
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      max-lifetime: 600

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  duration: 86_400_000 # 1 Day in miliseconds
  rsa:
    public: "dev_public.der"
    private: "dev_private.der"