name: Nexus & Dockerhub CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: 'nexus-grayroot'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "nexus-grayroot",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]

      - name: Deploy to nexus
        run: mvn -B deploy

      - name: Push the Docker image to Github registry
        run: |
          docker login --username grayr0ot --password ${{secrets.GHCR_PASSWORD}} ghcr.io
          docker build . --tag ghcr.io/grayr0ot/sh-authentication-service:prod
          docker push ghcr.io/grayr0ot/sh-authentication-service:prod